name: valet_pwa
description: "PWA para cliente"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ MÃ³dulo compartido local
  shared:
    path: ../../shared

  # ğŸ”¹ Ãconos y UI
  cupertino_icons: ^1.0.8

  # ğŸ”¹ Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1

  # ğŸ”¹ Almacenamiento local (offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ğŸ”¹ DetecciÃ³n de conectividad
  connectivity_plus: ^6.0.3

  # ğŸ”¹ Soporte PWA (para web)
  flutter_web_plugins:
    sdk: flutter

  mobile_scanner: ^6.0.1
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - shared/documents/privacy_policy.md

